version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: huysatoshi/udagram-reverseproxy:v1a
  backend-user:
    build:
      context: ./udagram-api-user
    image: huysatoshi/udagram-api-user:v1a
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: huysatoshi/udagram-api-feed:v1a
  frontend:
    build:
      context: ./udagram-frontend
    image: huysatoshi/udagram-frontend:local
